### ISSUE TITLE
End tag ignoring user-selected variables

### ISSUE THREAD

**Issue by EricJLange** [justinhunt/moodle-filter_generico#12]
Hi,

I think I found a real issue this time :) I created a test case here: [https://demo.poodll.com/mod/page/view.php?id=209](https://demo.poodll.com/mod/page/view.php?id=209)

The end tag will ignore the user selection, and use the default instead. In the case of a multi-select variable, the end tag uses the first default.

If my test page is overwritten, here's my test case:

**Body tag:**
```
<h4>Opening tag:</h4>
<b>One variable:</b> @@default_onevar@@
<br>

<b>List variable:</b> @@default_listvar@@
```

**End tag:**
```
<h4>End tag:</h4>
<b>One variable:</b>@@default_onevar@@
<br>

<b>List variable:</b> @@default_listvar@@
```

**Variable defaults:**
```
default_onevar="Default single variable",
default_listvar="Default list variable|Selected list variable"
```

**And the template call to test the above code:**
```
{GENERICO:type="endtag",default_onevar="My single variable",default_listvar="Selected list variable"}
{GENERICO:type="endtag_end"}
```

**The end result, rendered in Moodle:**

> ### Opening tag:
> **One variable:** My single variable
> **List variable:** Selected list variable
> ### End tag:
> **One variable:** Default single variable
> **List variable:** Default list variable

For added weirdness, omit the variables from the body code (keeping the end tag code) and the template will not present the drop down list for multi-select when using the Atto icon extension.

**Comment by justinhunt** [comment]
Hi Eric. Thanks for the report. I know exactly what you are referring to. It is because the variables from the opening tag are not available in the end tag. I would love to make them available there but I have never figured out a good way to do that. I do think its possible though.

When the generico tags are processed by the filter they are processed one at a time. I would need to add some sort of "parse and stash" logic during the opening tag processing. And then a "pickup and use" function during the end tag processing. 

Its worth doing and I will attempt it. But its weeks away at the moment.

**Comment by EricJLange** [comment]
Thanks Justin, for the quick reply! I'll rethink how I'm using the plugin for now- I used the end tag so I could provide a center section (between the body and end tags) where a course creator could add any number of bullet points in a list.  I couldn't think of a way to provide a variable number of bullet points (they will represent course objectives, and could be anywhere from 1 to N objectives).
I know there's probably a way to do this in Javascript but I'm not skilled enough there. ;)

I still really appreciate this plugin, it's saving me lots of time and effort in other places.

**Comment by justinhunt** [comment]
Interesting. Thats *exactly* what we have been doing on a project in Tokyo. Putting the learning objectives in bullets between Generico tags. Its better really to do it that way, than as params to Generico, because its much easier for ordinary people to edit. When I need to do anything really funky with the list, I use javascript. But for the most part css styling is enough

**Comment by EricJLange** [comment]
Yep, if my old Javascript skills weren't so rusty, I'd create an array and let the user provide 1 to N objectives (and then apply bullet points).

For now, I just added a second template. First template ends, then my objectives live in the text editor, then the second template begins (where I needed the variables to be picked up again). It's working great.

**Comment by justinhunt** [comment]
I will close this now, because there is no plan to add a parse/stash [open]  and parse/retrieve [end] feature. Though it would be nice, its an edge case and in cases where it would have been handy its always been possible to rework things to achieve the result
