### ISSUE TITLE
Generico codes in notification mails

### ISSUE THREAD

**Issue by superfoght** [justinhunt/moodle-filter_generico#29]
Hi

For a client of ours we have set up some different generico templates they use for their forum messages. For example a template for the users name, the course name (both full and shortname).

When a subscriber to a userforum is notified on a new message with the generico codes for these templates, the name is working as expected, but the coursename reverts to the name of the site.

Is this an issue? Is the filter not supported for mail usage?

**Comment by justinhunt** [comment]
Hi Bo

The Generico filter preloads a set of variables before parsing the the template and replacing the placeholders there.  We just use the global $COURSE variable to get the course data
(see :  https://github.com/justinhunt/moodle-filter_generico/blob/7ef2f206ee3b092299a82030187591622ea9f0b9/filter.php#L274)

In the mail function the course represented by $COURSE is different to the course in which the forum post is located. Since the filter will be called from the mail function , that is where $COURSE will be set.

If the courses are few, then one solution would be to have a different template per course, and hard code the coursename(s).

If the course list does not change much, another solution would be to have a drop down list of courses show in the Atto widget dialog, so the user could select the course when they insert the template.

If you are up for a hack/patch, then you might hack the atto widget so that it inserts the course id or name as an attribute on the Generico filter string when it inserts it onto the page. Then in your template you could use that name OR you could do a DB  search for the courseid, pull the correct course info and use that in the template.

Or simply not show the course name ....

**Comment by superfoght** [comment]
Thanks for the answer. That makes sense.
